/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/q7nKYGDieQ5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"

export function input() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <Link className="flex items-center gap-2 text-lg font-semibold md:text-base" href="#">
          <MountainIcon className="w-6 h-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="hidden md:flex md:items-center md:gap-5 lg:gap-6">
          <Link className="font-bold" href="#">
            Home
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Search
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Analytics
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Settings
          </Link>
        </nav>
        <div className="ml-auto flex items-center gap-2">
          <form className="flex-1 relative">
            <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
            <Input
              className="pl-8 sm:w-[300px] md:w-[200px] lg:w-[300px]"
              placeholder="Search groups..."
              type="search"
            />
          </form>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button className="rounded-full" size="icon" variant="ghost">
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="32"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32"
                />
                <span className="sr-only">Toggle user menu</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-[200px]">
              <DropdownMenuLabel>Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Profile</DropdownMenuItem>
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem className="text-red-600">Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <main className="flex-1 grid gap-6 p-4 md:p-10">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">Search Groups</h1>
            <form className="flex-1 relative w-full max-w-md">
              <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
              <Input className="pl-8 w-full" placeholder="Search groups..." type="search" />
            </form>
            <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400 h-fit">
              Discover and join the best groups for your interests.
            </p>
          </div>
        </div>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          <Card>
            <div className="flex justify-between items-center mb-2">
              <div className="text-xs text-gray-500 dark:text-gray-400">Created 2 days ago</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">123 members</div>
            </div>
            <CardHeader>
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="font-semibold">Group 1</div>
              </div>
            </CardHeader>
            <CardContent>
              <p>This is a description of Group 1.</p>
            </CardContent>
            <CardFooter className="flex justify-between items-center">
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="text-xs text-gray-500 dark:text-gray-400">Managed by John Doe</div>
              </div>
              <Button size="sm" variant="outline">
                Join
              </Button>
            </CardFooter>
          </Card>
          <Card>
            <div className="flex justify-between items-center mb-2">
              <div className="text-xs text-gray-500 dark:text-gray-400">Created 1 week ago</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">456 members</div>
            </div>
            <CardHeader>
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="font-semibold">Group 2</div>
              </div>
            </CardHeader>
            <CardContent>
              <p>This is a description of Group 2.</p>
            </CardContent>
            <CardFooter className="flex justify-between items-center">
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="text-xs text-gray-500 dark:text-gray-400">Managed by Jane Doe</div>
              </div>
              <Button size="sm" variant="outline">
                Join
              </Button>
            </CardFooter>
          </Card>
          <Card>
            <div className="flex justify-between items-center mb-2">
              <div className="text-xs text-gray-500 dark:text-gray-400">Created 3 weeks ago</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">789 members</div>
            </div>
            <CardHeader>
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="font-semibold">Group 3</div>
              </div>
            </CardHeader>
            <CardContent>
              <p>This is a description of Group 3.</p>
            </CardContent>
            <CardFooter className="flex justify-between items-center">
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="text-xs text-gray-500 dark:text-gray-400">Managed by John Smith</div>
              </div>
              <Button size="sm" variant="outline">
                Join
              </Button>
            </CardFooter>
          </Card>
          <Card>
            <div className="flex justify-between items-center mb-2">
              <div className="text-xs text-gray-500 dark:text-gray-400">Created 1 month ago</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">321 members</div>
            </div>
            <CardHeader>
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="font-semibold">Group 4</div>
              </div>
            </CardHeader>
            <CardContent>
              <p>This is a description of Group 4.</p>
            </CardContent>
            <CardFooter className="flex justify-between items-center">
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="text-xs text-gray-500 dark:text-gray-400">Managed by Jane Smith</div>
              </div>
              <Button size="sm" variant="outline">
                Join
              </Button>
            </CardFooter>
          </Card>
          <Card>
            <div className="flex justify-between items-center mb-2">
              <div className="text-xs text-gray-500 dark:text-gray-400">Created 2 months ago</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">654 members</div>
            </div>
            <CardHeader>
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="font-semibold">Group 5</div>
              </div>
            </CardHeader>
            <CardContent>
              <p>This is a description of Group 5.</p>
            </CardContent>
            <CardFooter className="flex justify-between items-center">
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="text-xs text-gray-500 dark:text-gray-400">Managed by John Doe</div>
              </div>
              <Button size="sm" variant="outline">
                Join
              </Button>
            </CardFooter>
          </Card>
          <Card>
            <div className="flex justify-between items-center mb-2">
              <div className="text-xs text-gray-500 dark:text-gray-400">Created 3 months ago</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">987 members</div>
            </div>
            <CardHeader>
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="font-semibold">Group 6</div>
              </div>
            </CardHeader>
            <CardContent>
              <p>This is a description of Group 6.</p>
            </CardContent>
            <CardFooter className="flex justify-between items-center">
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="text-xs text-gray-500 dark:text-gray-400">Managed by Jane Smith</div>
              </div>
              <Button size="sm" variant="outline">
                Join
              </Button>
            </CardFooter>
          </Card>
          <Card>
            <div className="flex justify-between items-center mb-2">
              <div className="text-xs text-gray-500 dark:text-gray-400">Created 4 months ago</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">159 members</div>
            </div>
            <CardHeader>
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="font-semibold">Group 7</div>
              </div>
            </CardHeader>
            <CardContent>
              <p>This is a description of Group 7.</p>
            </CardContent>
            <CardFooter className="flex justify-between items-center">
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="text-xs text-gray-500 dark:text-gray-400">Managed by John Doe</div>
              </div>
              <Button size="sm" variant="outline">
                Join
              </Button>
            </CardFooter>
          </Card>
          <Card>
            <div className="flex justify-between items-center mb-2">
              <div className="text-xs text-gray-500 dark:text-gray-400">Created 5 months ago</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">234 members</div>
            </div>
            <CardHeader>
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="font-semibold">Group 8</div>
              </div>
            </CardHeader>
            <CardContent>
              <p>This is a description of Group 8.</p>
            </CardContent>
            <CardFooter className="flex justify-between items-center">
              <div className="flex items-center gap-2">
                <Avatar className="w-6 h-6 border">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback />
                </Avatar>
              </div>
            </CardFooter>
          </Card>
        </div>
      </main>
    </div>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
